# Generated by Django 4.1 on 2022-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu',
            new_name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Address',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
