# Generated by Django 4.1 on 2022-09-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_menu_title_menu_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='day',
            field=models.IntegerField(choices=[(0, 'day'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=0),
        ),
    ]
