# Generated by Django 4.1 on 2022-09-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_menu_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='votes',
            field=models.IntegerField(null=True),
        ),
    ]
