# Generated by Django 4.1 on 2022-09-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_menu_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
