# Generated by Django 4.1 on 2022-09-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevote',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
